[package]
name = "scylladb_reconnects"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"

[[bin]]
name = "scylladb_reconnects"
path = "scylladb_reconnects.rs"
